sudo: false

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install: pip install tox-travis
script: tox

cache: pip

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.9"
  include:
    - python: "3.7"
      dist: xenial
      sudo: required

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/4792e76205b696e243ff
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always

